# These are supported funding model platforms

github: Pranjal-Prabhat
patreon: Pranjal-Prabhat
open_collective: Pranjal-Prabhat
ko_fi: Pranjal-Prabhat
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: #
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
polar: # Replace with a single Polar username
buy_me_a_coffee: Pranjal-Prabhat
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
